<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.experitest.IOSDemo" tests="2" time="53.324" ignored="4" failures="0" timestamp="14 Nov 2018 08:41:36 GMT" skipped="0" hostname="vchand-lt" errors="1">
  <testcase name="testESPN" time="28.900" classname="com.experitest.IOSDemo"/>
  <testcase name="testEribank" time="24.424" classname="com.experitest.IOSDemo">
    <error type="com.experitest.client.InternalException" message="Exception caught while executing elementSendText: Element was not identified: &#039;hint=Username&#039; at zone NATIVE">
      <![CDATA[com.experitest.client.InternalException: Exception caught while executing elementSendText: Element was not identified: 'hint=Username' at zone NATIVE
	at com.experitest.client.JavaClientInternals.executeInternally(JavaClientInternals.java:286)
	at com.experitest.client.Client.execute(Client.java:247)
	at com.experitest.client.Client.elementSendText(Client.java:824)
	at com.experitest.IOSDemo.testEribank(IOSDemo.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1289)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testEribank -->
  <testcase name="testEribank" classname="com.experitest.IOSDemo">
    <skipped/>
  </testcase> <!-- testEribank -->
  <testcase name="testESPN" classname="com.experitest.IOSDemo">
    <skipped/>
  </testcase> <!-- testESPN -->
  <testcase name="testTouchMeNot" classname="com.experitest.IOSDemo">
    <skipped/>
  </testcase> <!-- testTouchMeNot -->
  <testcase name="testTouchMeNot" classname="com.experitest.IOSDemo">
    <skipped/>
  </testcase> <!-- testTouchMeNot -->
</testsuite> <!-- com.experitest.IOSDemo -->
